#ifndef PSRDADA_CPP_EFFELSBERG_EDD_SPECTRALKURTOSISCUDA_CUH
#define PSRDADA_CPP_EFFELSBERG_EDD_SPECTRALKURTOSISCUDA_CUH

#include "psrdada_cpp/common.hpp"
#include <thrust/device_vector.h>
#include <thrust/host_vector.h>
#include <thrust/complex.h>
#include <thrust/copy.h>
#include <thrust/transform.h>
#include <thrust/functional.h>
#include <thrust/iterator/transform_iterator.h>
#include <thrust/iterator/discard_iterator.h>
#include <thrust/execution_policy.h>
#include <nvToolsExt.h>

namespace psrdada_cpp {
namespace effelsberg {
namespace edd {

#define BLOCK_DIM 1024

struct RFIStatistics{
    thrust::device_vector<int> rfi_status;
    float rfi_fraction;
};

class SpectralKurtosisCuda{
public:
    /**
     * @brief      constructor
     *
     * @param(in)  nchannels     number of channels.
     * @param(in)  window_size   number of samples per window.
     * @param(in)  sk_min        minimum value of spectral kurtosis.
     * @param(in)  sk_max        maximum value of spectral kurtosis.
     */
    SpectralKurtosisCuda(std::size_t nchannels, std::size_t window_size, float sk_min = 0.8,
                         float sk_max = 1.2);
    ~SpectralKurtosisCuda();

    /**
     * @brief      computes spectral kurtosis for the given data using thrust calls and returns its rfi statistics.
     *             This is used to compare and verify  the results generated by compute_sk - an optimized kernel implementation.
     *
     * @param(in)  data          input data
     * @param(out) stats         RFI statistics
     *
     */
    void compute_sk_thrust(thrust::device_vector<thrust::complex<float>> const& data, RFIStatistics &stats);

    /**
     * @brief      computes spectral kurtosis (using optimized kernel function) for the given data and returns its rfi statistics.
     *
     * @param(in)  data          input data
     * @param(out) stats         RFI statistics
     *
     */
    void compute_sk(thrust::device_vector<thrust::complex<float>> &data, RFIStatistics &stats);

private:
    /**
     * @brief     initializes the data members of the class.
     *
     * */
    void init();
    std::size_t _nchannels; //number of channels
    std::size_t _window_size; //window size
    std::size_t _nwindows; //number of windows
    std::size_t _sample_size; //size of input data
    float _sk_min, _sk_max;
    thrust::device_vector<float> _d_s1, _d_s2;
    cudaStream_t _stream;
};
} //edd
} //effelsberg
} //psrdada_cpp

#endif //PSRDADA_CPP_EFFELSBERG_EDD_SPECTRALKURTOSISCUDA_CUH
